#!/bin/bash
# ============================================================
# RiVision Node Docker 入口脚本
#
# 功能:
#   1. 生成 /app/.env (供 scripts 和 node-agent 读取)
#   2. 初始化模型配置 (active-model.sh)
#   3. 验证关键文件
#   4. 启动 supervisord
# ============================================================
set -e

echo "╔══════════════════════════════════════════════╗"
echo "║   RiVision Node (Docker)                     ║"
echo "╚══════════════════════════════════════════════╝"

# ─── 1. 生成 .env 文件 ─────────────────────────────────────
# scripts (start-llama.sh 等) 通过 source .env 读取配置
cat > /app/.env << EOF
# Auto-generated by Docker entrypoint
NODE_ID=${NODE_ID:-$(hostname)}
GATEWAY_URL=${GATEWAY_URL:-http://192.168.122.1:8081}
REGISTRATION_TOKEN=${REGISTRATION_TOKEN:-}
NODE_HOST=${NODE_HOST:-auto}
NODE_TAGS=${NODE_TAGS:-riscv,k3,docker}
AGENT_HOST=${AGENT_HOST:-0.0.0.0}
AGENT_PORT=${AGENT_PORT:-9090}
LLAMA_PORT=${LLAMA_PORT:-9080}
LLAMA_THREADS=${LLAMA_THREADS:-8}
LLAMA_BATCH_THREADS=${LLAMA_BATCH_THREADS:-8}
LLAMA_CPU_AFFINITY=${LLAMA_CPU_AFFINITY:-}
LLAMA_CTX_SIZE=${LLAMA_CTX_SIZE:-4096}
LLAMA_PARALLEL=${LLAMA_PARALLEL:-1}
LLAMA_FLASH_ATTN=${LLAMA_FLASH_ATTN:-true}
LLAMA_BUILD_DIR=${LLAMA_BUILD_DIR:-/app/llama.cpp/build-k3}
HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-10}
LOG_LEVEL=${LOG_LEVEL:-INFO}
LOG_ENABLE=${LOG_ENABLE:-true}
LOG_FILE=${LOG_FILE:-/app/logs/node-agent.log}
EOF

# 复制 .env 到 node-agent 目录 (config.py env_file = "../.env" 需要)
cp /app/.env /app/node-agent/.env 2>/dev/null || true

echo "[INFO] .env 已生成"

# ─── 1.5. 初始化 config volume ─────────────────────────────
# Docker volume 首次挂载时为空，从默认配置恢复
if [ -d "/app/config.default" ] && [ ! -f "/app/config/models.conf" ]; then
    echo "[INFO] 初始化 config volume (首次运行)"
    cp -n /app/config.default/* /app/config/ 2>/dev/null || true
fi

# ─── 2. 初始化模型配置 ─────────────────────────────────────
# 如果 active-model.sh 不存在或模型路径无效，自动配置
ACTIVE_CONFIG="/app/config/active-model.sh"
NEED_SWITCH=false

if [ ! -f "$ACTIVE_CONFIG" ]; then
    NEED_SWITCH=true
    echo "[INFO] 未找到 active-model.sh，需要初始化"
else
    # 检查已配置模型文件是否存在
    source "$ACTIVE_CONFIG"
    if [ ! -f "${ACTIVE_MODEL_FILE:-/nonexistent}" ]; then
        NEED_SWITCH=true
        echo "[WARN] 已配置模型文件不存在: ${ACTIVE_MODEL_FILE:-未设置}"
    else
        echo "[INFO] 当前模型: ${ACTIVE_MODEL_NAME:-unknown}"
    fi
fi

if $NEED_SWITCH; then
    MODEL="${DEFAULT_MODEL:-fastvlm-0.5b-q8}"
    echo "[INFO] 自动配置模型: $MODEL"
    
    # 确保 config 和 models.conf 存在
    if [ -f "/app/config/models.conf" ] && [ -d "/app/models" ]; then
        bash /app/scripts/switch-model.sh "$MODEL" 2>/dev/null || {
            echo "[WARN] switch-model.sh 失败，尝试列出可用模型..."
            bash /app/scripts/switch-model.sh --list 2>/dev/null || true
            echo "[WARN] 请确保模型文件已挂载到 /app/models/"
        }
    else
        echo "[WARN] 缺少 models.conf 或 models 目录"
    fi
fi

# ─── 3. 验证关键文件 ───────────────────────────────────────
echo ""
echo "─── 环境检查 ───"

# llama.cpp 二进制
LLAMA_BIN="${LLAMA_BUILD_DIR:-/app/llama.cpp/build-k3}/bin"
if [ -x "$LLAMA_BIN/llama-server" ]; then
    echo "[OK] llama-server: $LLAMA_BIN/llama-server"
elif [ -x "$LLAMA_BIN/llama-mtmd-cli" ]; then
    echo "[OK] llama-mtmd-cli: $LLAMA_BIN/llama-mtmd-cli (fallback)"
else
    echo "[FAIL] llama 二进制未找到: $LLAMA_BIN/"
    echo "       请先在 K3 上编译: scripts/build.sh"
fi

# 模型文件
MODEL_COUNT=$(find /app/models -name "*.gguf" 2>/dev/null | wc -l)
echo "[INFO] 模型文件: $MODEL_COUNT 个 GGUF"
find /app/models -name "*.gguf" -exec basename {} \; 2>/dev/null | while read f; do
    echo "       - $f"
done

# Node Agent
if python -c "import fastapi, uvicorn, psutil" 2>/dev/null; then
    echo "[OK] Node Agent 依赖完整"
else
    echo "[FAIL] Node Agent 依赖缺失"
fi

echo ""
echo "[INFO] Gateway: ${GATEWAY_URL:-未配置}"
echo "[INFO] Llama Port: ${LLAMA_PORT:-9080}"
echo "[INFO] Agent Port: ${AGENT_PORT:-9090}"
echo "[INFO] 线程: ${LLAMA_THREADS:-8}"
echo ""

# ─── 4. 启动 supervisord ──────────────────────────────────
exec "$@"
