// Package owl provides a production-grade HTTP client for rivision_owl's REST API.
//
// Architecture:
//
//	rivision_owl (Host-side) handles all protocol-level complexity:
//	  - GB28181: SIP REGISTER/INVITE → RTP → ZLMediaKit → RTSP
//	  - ONVIF:  WS-Discovery → GetStreamUri → RTSP
//	  - RTMP/RTSP: stream proxy via ZLMediaKit
//
//	Hub calls OWL HTTP API to:
//	  1. Add/manage devices (GB28181 / ONVIF)
//	  2. Trigger playback → get RTSP URLs
//	  3. Discover ONVIF cameras on the network
//	  4. Retrieve snapshots, control PTZ
//
//	Hub then assigns the resolved RTSP URLs to Workers via scheduler.
//	Workers never handle GB28181/ONVIF directly — only plain RTSP.
//
// Production features (ported from rivision_cli):
//   - Authentication: Plain + RSA OAEP/SHA256 dual-mode with auto-fallback
//   - API path fallbacks: /api/xxx → /xxx for GoWVP vs rivision_owl compat
//   - Response parsing: auto-detect {code,msg,data} wrapped vs direct JSON
//   - Pagination: full traversal with dedup and loop protection
//   - RTSP URL caching: 5min TTL to avoid repeated SIP INVITE
//   - Token refresh: auto re-login on 401 and retry
package owl

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"
)

// Config holds OWL integration configuration for Hub.
type Config struct {
	URL          string        `yaml:"url" json:"url"`                     // OWL HTTP API base URL (default http://localhost:15123)
	Username     string        `yaml:"username" json:"username"`           // OWL login username
	Password     string        `yaml:"password" json:"password"`           // OWL login password
	UseRSAAuth   bool          `yaml:"use_rsa_auth" json:"use_rsa_auth"`  // use RSA OAEP login (GoWVP mode)
	PollInterval time.Duration `yaml:"poll_interval" json:"poll_interval"` // device status poll interval (default 60s)
	Enabled      bool          `yaml:"enabled" json:"enabled"`
	CacheTTL     time.Duration `yaml:"cache_ttl" json:"cache_ttl"`        // RTSP URL cache TTL (default 5min)
}

// DefaultConfig returns production defaults.
func DefaultConfig() Config {
	return Config{
		URL:          "http://localhost:15123",
		PollInterval: 60 * time.Second,
		CacheTTL:     5 * time.Minute,
		Enabled:      true,
	}
}

// --- OWL API response types ---

// Device mirrors rivision_owl's ipc.Device.
type Device struct {
	ID           string    `json:"id"`
	Type         string    `json:"type"`         // GB28181 | ONVIF | RTSP | RTMP
	DeviceID     string    `json:"device_id"`    // 20-digit GB28181 ID or OWL internal ID
	Name         string    `json:"name"`
	Manufacturer string    `json:"manufacturer"`
	Model        string    `json:"model"`
	IP           string    `json:"ip"`
	Port         int       `json:"port"`
	IsOnline     bool      `json:"is_online"`
	Transport    string    `json:"transport"`
	Channels     int       `json:"channels"`
	Children     []Channel `json:"children,omitempty"`
	CreatedAt    string    `json:"created_at"`
	UpdatedAt    string    `json:"updated_at"`
}

// Channel mirrors rivision_owl's ipc.Channel.
type Channel struct {
	ID           string `json:"id"`
	DID          string `json:"did"`
	DeviceID     string `json:"device_id"`
	ChannelID    string `json:"channel_id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	IsOnline     bool   `json:"is_online"`
	IsPlaying    bool   `json:"is_playing"`
	HasRecording bool   `json:"has_recording"`
	PTZType      int    `json:"ptz_type"`
	App          string `json:"app"`
	Stream       string `json:"stream"`
	Manufacturer string `json:"manufacturer"`
	Model        string `json:"model"`
	Firmware     string `json:"firmware"`
	StreamURL    string `json:"stream_url,omitempty"` // ONVIF/RTSP: direct camera RTSP URL
	DeviceIP     string `json:"device_ip,omitempty"`  // device IP (for direct access)
}

// PlayResult is the response from POST /channels/:id/play.
type PlayResult struct {
	App     string           `json:"app"`
	Stream  string           `json:"stream"`
	Session string           `json:"session"`
	Items   []StreamLiveAddr `json:"items"`
	URLs    map[string]string `json:"urls,omitempty"` // compat: GoWVP flat format
}

// StreamLiveAddr contains streaming URLs generated by ZLMediaKit.
type StreamLiveAddr struct {
	RTSP    string `json:"rtsp,omitempty"`
	RTMP    string `json:"rtmp,omitempty"`
	HTTP    string `json:"http,omitempty"`     // HTTP-FLV (rivision_owl)
	HTTPFLV string `json:"http_flv,omitempty"` // HTTP-FLV (GoWVP)
	HTTPS   string `json:"https,omitempty"`
	WS      string `json:"ws,omitempty"`       // WebSocket-FLV
	WSS     string `json:"wss,omitempty"`
	HLS     string `json:"hls,omitempty"`
	FMP4    string `json:"fmp4,omitempty"`
	WebRTC  string `json:"webrtc,omitempty"`
}

// AddDeviceRequest is the payload for POST /devices.
type AddDeviceRequest struct {
	Type     string `json:"type"`                // GB28181 | ONVIF
	DeviceID string `json:"device_id,omitempty"` // 20-digit GB28181 ID
	Name     string `json:"name"`
	IP       string `json:"ip,omitempty"`
	Port     int    `json:"port,omitempty"`
	Username string `json:"username,omitempty"` // ONVIF auth
	Password string `json:"password,omitempty"` // ONVIF auth
}

// ServerInfo OWL server status info.
type ServerInfo struct {
	Version  string `json:"version"`
	UpTime   int64  `json:"up_time"`
	Channels int    `json:"channels"`
	Devices  int    `json:"devices"`
	Streams  int    `json:"streams"`
}

// Capabilities reports which OWL API features are available.
type Capabilities struct {
	Login               bool `json:"login"`
	ServerInfo          bool `json:"server_info"`
	Channels            bool `json:"channels"`
	Devices             bool `json:"devices"`
	DevicesWithChannels bool `json:"devices_with_channels"`
	Play                bool `json:"play"`
	Snapshot            bool `json:"snapshot"`
	PTZ                 bool `json:"ptz"`
}

// --- RTSP cache entry ---

const maxCacheSize = 1000 // max cached RTSP URLs

type rtspCacheEntry struct {
	url       string
	expiresAt time.Time
}

// Client is the Hub-side HTTP client for rivision_owl (production-grade).
type Client struct {
	cfg     Config
	baseURL string
	client  *http.Client

	// Auth state
	mu     sync.RWMutex
	token  string
	rsaKey *rsa.PublicKey

	// RTSP URL cache to avoid repeated SIP INVITE
	cacheMu   sync.RWMutex
	rtspCache map[string]*rtspCacheEntry
}

// NewClient creates an OWL API client.
func NewClient(cfg Config) *Client {
	baseURL := cfg.URL
	if baseURL == "" {
		baseURL = "http://localhost:15123"
	}
	baseURL = strings.TrimRight(baseURL, "/")

	if cfg.CacheTTL == 0 {
		cfg.CacheTTL = 5 * time.Minute
	}

	return &Client{
		cfg:       cfg,
		baseURL:   baseURL,
		client:    &http.Client{Timeout: 30 * time.Second},
		rtspCache: make(map[string]*rtspCacheEntry),
	}
}

// IsEnabled reports whether the client is configured and enabled.
func (c *Client) IsEnabled() bool {
	return c.cfg.Enabled && c.baseURL != ""
}

// ─── Authentication ─────────────────────────────────────────────────────────

// Login authenticates with OWL and stores the token.
// Auto-fallback: plain → RSA (or RSA → plain if UseRSAAuth is set).
func (c *Client) Login(ctx context.Context) error {
	if c.cfg.Username == "" {
		return nil // no auth configured, assume open API
	}

	if c.cfg.UseRSAAuth {
		if err := c.loginRSA(ctx); err == nil {
			return nil
		}
		// RSA failed → try plain
		if err := c.loginPlain(ctx); err == nil {
			return nil
		}
		return fmt.Errorf("owl login failed (RSA+plain fallback)")
	}

	// Default: plain first, fallback to RSA
	if err := c.loginPlain(ctx); err == nil {
		return nil
	}
	if err := c.loginRSA(ctx); err == nil {
		return nil
	}
	return fmt.Errorf("owl login failed (plain+RSA fallback)")
}

// EnsureLogin triggers login only if token is empty.
func (c *Client) EnsureLogin(ctx context.Context) error {
	if c.cfg.Username == "" {
		return nil
	}
	c.mu.RLock()
	hasToken := c.token != ""
	c.mu.RUnlock()
	if hasToken {
		return nil
	}
	return c.Login(ctx)
}

func (c *Client) loginPlain(ctx context.Context) error {
	data := map[string]interface{}{
		"username": c.cfg.Username,
		"password": c.cfg.Password,
	}
	body, err := c.doPostRaw(ctx, c.baseURL+"/login", data)
	if err != nil {
		return fmt.Errorf("plain login: %w", err)
	}
	return c.extractToken(body, "plain")
}

func (c *Client) loginRSA(ctx context.Context) error {
	pubKey, err := c.getRSAPublicKey(ctx)
	if err != nil {
		return fmt.Errorf("get RSA key: %w", err)
	}

	credJSON, _ := json.Marshal(map[string]string{
		"username": c.cfg.Username,
		"password": c.cfg.Password,
	})

	ciphertext, err := rsa.EncryptOAEP(sha256.New(), rand.Reader, pubKey, credJSON, nil)
	if err != nil {
		return fmt.Errorf("RSA encrypt: %w", err)
	}

	data := map[string]string{
		"data": base64.StdEncoding.EncodeToString(ciphertext),
	}
	body, err := c.doPostRaw(ctx, c.baseURL+"/login", data)
	if err != nil {
		return fmt.Errorf("RSA login: %w", err)
	}
	return c.extractToken(body, "RSA")
}

func (c *Client) getRSAPublicKey(ctx context.Context) (*rsa.PublicKey, error) {
	c.mu.RLock()
	if c.rsaKey != nil {
		defer c.mu.RUnlock()
		return c.rsaKey, nil
	}
	c.mu.RUnlock()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.baseURL+"/login/key", nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetch RSA key: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<16))
	var keyResp struct {
		Key string `json:"key"`
	}
	if err := json.Unmarshal(body, &keyResp); err != nil {
		return nil, fmt.Errorf("parse RSA key response: %w", err)
	}

	pemData, err := base64.StdEncoding.DecodeString(keyResp.Key)
	if err != nil {
		return nil, fmt.Errorf("decode base64 PEM: %w", err)
	}

	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("PEM decode failed")
	}

	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse public key: %w", err)
	}

	rsaPub, ok := pub.(*rsa.PublicKey)
	if !ok {
		return nil, fmt.Errorf("not an RSA public key")
	}

	c.mu.Lock()
	c.rsaKey = rsaPub
	c.mu.Unlock()
	return rsaPub, nil
}

func (c *Client) extractToken(body []byte, method string) error {
	// Try direct {token: "..."} format
	var direct struct {
		Token string `json:"token"`
	}
	if json.Unmarshal(body, &direct) == nil && direct.Token != "" {
		c.mu.Lock()
		c.token = direct.Token
		c.mu.Unlock()
		return nil
	}

	// Try wrapped {code, data: {token}} format
	var wrapped struct {
		Code int             `json:"code"`
		Data json.RawMessage `json:"data"`
	}
	if json.Unmarshal(body, &wrapped) == nil && len(wrapped.Data) > 0 {
		if json.Unmarshal(wrapped.Data, &direct) == nil && direct.Token != "" {
			c.mu.Lock()
			c.token = direct.Token
			c.mu.Unlock()
			return nil
		}
	}

	return fmt.Errorf("%s login: no token in response", method)
}

// clearToken forces re-authentication on next request.
func (c *Client) clearToken() {
	c.mu.Lock()
	c.token = ""
	c.mu.Unlock()
}

// ─── Server Info ─────────────────────────────────────────────────────────────

// GetServerInfo returns OWL server info (with fallback paths).
func (c *Client) GetServerInfo(ctx context.Context) (*ServerInfo, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	var info ServerInfo
	for _, path := range []string{"/api/server/info", "/health"} {
		body, err := c.doGetAuth(ctx, c.baseURL+path)
		if err != nil {
			continue
		}
		parsed, err := c.parseResponse(body)
		if err != nil {
			continue
		}
		if json.Unmarshal(parsed, &info) == nil && info.Version != "" {
			return &info, nil
		}
	}
	return nil, fmt.Errorf("server info endpoint unavailable")
}

// ProbeCapabilities checks which OWL API endpoints are available.
func (c *Client) ProbeCapabilities(ctx context.Context) *Capabilities {
	caps := &Capabilities{}

	if err := c.Login(ctx); err == nil {
		caps.Login = true
	}
	if _, err := c.GetServerInfo(ctx); err == nil {
		caps.ServerInfo = true
	}
	if _, err := c.ListChannels(ctx); err == nil {
		caps.Channels = true
	}
	if _, err := c.ListDevices(ctx); err == nil {
		caps.Devices = true
	}
	if _, err := c.ListDevicesWithChannels(ctx); err == nil {
		caps.DevicesWithChannels = true
	}
	caps.Play = caps.Channels || caps.DevicesWithChannels
	caps.Snapshot = caps.Play
	caps.PTZ = caps.Play

	return caps
}

// ─── Device management ──────────────────────────────────────────────────────

// ListDevicesWithChannels returns all devices and their child channels.
func (c *Client) ListDevicesWithChannels(ctx context.Context) ([]Device, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	params := "page=1&size=200"

	// Try multiple paths for GoWVP vs rivision_owl compatibility
	for _, path := range []string{"/api/devices/channels", "/devices/channels"} {
		body, err := c.doGetAuthRetry(ctx, c.baseURL+path+"?"+params)
		if err != nil {
			continue
		}
		devices, err := c.parseDeviceList(body)
		if err == nil {
			return devices, nil
		}
	}
	return nil, fmt.Errorf("devices/channels endpoint unavailable")
}

// ListDevices returns all devices (without channels).
func (c *Client) ListDevices(ctx context.Context) ([]Device, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	params := "page=1&size=200"

	for _, path := range []string{"/api/devices", "/devices"} {
		body, err := c.doGetAuthRetry(ctx, c.baseURL+path+"?"+params)
		if err != nil {
			continue
		}
		devices, err := c.parseDeviceList(body)
		if err == nil {
			return devices, nil
		}
	}

	// Fallback: extract from devices/channels
	devs, err := c.ListDevicesWithChannels(ctx)
	if err != nil {
		return nil, fmt.Errorf("devices endpoint unavailable")
	}
	for i := range devs {
		devs[i].Children = nil
	}
	return devs, nil
}

// AddDevice registers a GB28181 or ONVIF device in OWL.
func (c *Client) AddDevice(ctx context.Context, req AddDeviceRequest) (*Device, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	reqBody, _ := json.Marshal(req)

	for _, path := range []string{"/api/devices", "/devices"} {
		body, err := c.doPostAuth(ctx, c.baseURL+path, reqBody)
		if err != nil {
			continue
		}
		parsed, err := c.parseResponse(body)
		if err != nil {
			continue
		}
		var dev Device
		if json.Unmarshal(parsed, &dev) == nil && dev.ID != "" {
			return &dev, nil
		}
	}
	return nil, fmt.Errorf("AddDevice: all endpoints failed")
}

// DeleteDevice removes a device from OWL.
func (c *Client) DeleteDevice(ctx context.Context, deviceID string) error {
	if err := c.EnsureLogin(ctx); err != nil {
		return err
	}

	escaped := url.PathEscape(deviceID)
	for _, path := range []string{"/api/devices/", "/devices/"} {
		_, err := c.doDeleteAuth(ctx, c.baseURL+path+escaped)
		if err == nil {
			return nil
		}
	}
	return fmt.Errorf("DeleteDevice %s: all endpoints failed", deviceID)
}

// RefreshCatalog triggers a device catalog refresh.
func (c *Client) RefreshCatalog(ctx context.Context, deviceID string) error {
	if err := c.EnsureLogin(ctx); err != nil {
		return err
	}

	escaped := url.PathEscape(deviceID)
	for _, path := range []string{"/api/devices/%s/catalog", "/devices/%s/catalog"} {
		_, err := c.doPostAuth(ctx, c.baseURL+fmt.Sprintf(path, escaped), nil)
		if err == nil {
			return nil
		}
	}
	return fmt.Errorf("RefreshCatalog: endpoint unavailable")
}

// ─── Channel operations ─────────────────────────────────────────────────────

// ListChannels returns channels (first page). Use GetAllChannels for full list.
func (c *Client) ListChannels(ctx context.Context) ([]Channel, error) {
	return c.listChannelsPage(ctx, 1, 200, "")
}

// ListChannelsByDevice returns channels for a specific device.
func (c *Client) ListChannelsByDevice(ctx context.Context, deviceID string) ([]Channel, error) {
	return c.listChannelsPage(ctx, 1, 200, deviceID)
}

// GetAllChannels returns ALL channels across all pages with dedup.
func (c *Client) GetAllChannels(ctx context.Context) ([]Channel, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	var all []Channel
	seen := make(map[string]struct{})
	pageSize := 100
	maxPages := 20

	for page := 1; page <= maxPages; page++ {
		items, err := c.listChannelsPage(ctx, page, pageSize, "")
		if err != nil {
			if page == 1 {
				return nil, err
			}
			break
		}

		added := 0
		for _, ch := range items {
			id := ch.ID
			if id == "" {
				id = ch.ChannelID
			}
			if id == "" {
				continue
			}
			if _, ok := seen[id]; ok {
				continue
			}
			seen[id] = struct{}{}
			all = append(all, ch)
			added++
		}

		// Loop protection: no new items or empty page
		if len(items) == 0 || added == 0 {
			break
		}
		if len(all) >= len(items)*maxPages {
			break
		}
	}
	return all, nil
}

// GetChannel returns a single channel by ID.
func (c *Client) GetChannel(ctx context.Context, channelID string) (*Channel, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	escaped := url.PathEscape(channelID)
	for _, path := range []string{"/api/channels/", "/channels/"} {
		body, err := c.doGetAuthRetry(ctx, c.baseURL+path+escaped)
		if err != nil {
			continue
		}
		parsed, err := c.parseResponse(body)
		if err != nil {
			continue
		}
		var ch Channel
		if json.Unmarshal(parsed, &ch) == nil && (ch.ID != "" || ch.ChannelID != "") {
			return &ch, nil
		}
	}
	return nil, fmt.Errorf("GetChannel %s: not found", channelID)
}

func (c *Client) listChannelsPage(ctx context.Context, page, pageSize int, deviceID string) ([]Channel, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	params := url.Values{}
	params.Set("page", fmt.Sprintf("%d", page))
	params.Set("size", fmt.Sprintf("%d", pageSize))
	if deviceID != "" {
		params.Set("device_id", deviceID)
	}
	qs := params.Encode()

	// Try channel endpoints with path fallback
	for _, path := range []string{"/api/channels", "/channels"} {
		body, err := c.doGetAuthRetry(ctx, c.baseURL+path+"?"+qs)
		if err != nil {
			continue
		}
		channels, err := c.parseChannelList(body)
		if err == nil && len(channels) > 0 {
			return channels, nil
		}
	}

	// Fallback: extract channels from devices/channels
	devs, err := c.ListDevicesWithChannels(ctx)
	if err != nil {
		return nil, fmt.Errorf("channels endpoint unavailable")
	}
	var channels []Channel
	for _, d := range devs {
		if deviceID != "" && d.ID != deviceID && d.DeviceID != deviceID {
			continue
		}
		for _, ch := range d.Children {
			if ch.DeviceID == "" {
				ch.DeviceID = d.ID
			}
			channels = append(channels, ch)
		}
	}
	return channels, nil
}

// ─── Playback ───────────────────────────────────────────────────────────────

// PlayChannel triggers playback and returns streaming URLs.
// Supports both rivision_owl (items array) and GoWVP (URLs map) response formats.
func (c *Client) PlayChannel(ctx context.Context, channelID string) (*PlayResult, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	escaped := url.PathEscape(channelID)

	for _, path := range []string{"/api/channels/%s/play", "/channels/%s/play"} {
		body, err := c.doPostAuthRetry(ctx, c.baseURL+fmt.Sprintf(path, escaped), nil)
		if err != nil {
			continue
		}
		result, err := c.parsePlayResult(body)
		if err == nil {
			return result, nil
		}
	}
	return nil, fmt.Errorf("PlayChannel %s: all endpoints failed", channelID)
}

// PlayRemoteRequest directs Hub OWL to send SIP INVITE with a remote ZLM as media target.
// Camera sends RTP directly to the specified ZLM (on Worker machine), not to Hub's local ZLM.
type PlayRemoteRequest struct {
	ZLMHost     string `json:"zlm_host"`                // Worker ZLM IP
	ZLMHTTPPort int    `json:"zlm_http_port,omitempty"` // Worker ZLM HTTP API port (default 80)
	ZLMRTPPort  int    `json:"zlm_rtp_port,omitempty"`  // 0 = auto-allocate
}

// PlayRemote tells Hub OWL to set up a stream with media going to a remote Worker ZLM.
// Hub OWL handles SIP signaling (INVITE/BYE), but video flows Camera→Worker ZLM directly.
// Returns streaming URLs on the remote ZLM.
func (c *Client) PlayRemote(ctx context.Context, channelID string, req PlayRemoteRequest) (*PlayResult, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	escaped := url.PathEscape(channelID)
	payload, _ := json.Marshal(req)

	// Try play-remote endpoint first, fallback to standard play with query params
	for _, path := range []string{
		"/api/channels/%s/play-remote",
		"/channels/%s/play-remote",
	} {
		body, err := c.doPostAuthRetry(ctx, c.baseURL+fmt.Sprintf(path, escaped), payload)
		if err != nil {
			continue
		}
		result, err := c.parsePlayResult(body)
		if err == nil {
			return result, nil
		}
	}

	// Do NOT fall back to standard PlayChannel — that would route media to Hub's local ZLM,
	// violating the "Hub zero video" architecture. Instead, return an error so the caller
	// can handle it explicitly (e.g., switch to worker_owl mode or alert the operator).
	return nil, fmt.Errorf("PlayRemote not supported by OWL at %s for channel %s: cannot route media to Worker %s (play-remote endpoint unavailable)", c.baseURL, channelID, req.ZLMHost)
}

// StopChannel stops playback of a channel.
func (c *Client) StopChannel(ctx context.Context, channelID string) error {
	if err := c.EnsureLogin(ctx); err != nil {
		return err
	}

	escaped := url.PathEscape(channelID)
	for _, path := range []string{"/api/channels/%s/stop", "/channels/%s/stop"} {
		_, err := c.doPostAuth(ctx, c.baseURL+fmt.Sprintf(path, escaped), nil)
		if err == nil {
			return nil
		}
	}
	// Stop is best-effort; don't fail if endpoint is missing
	return nil
}

// GetSnapshotURL returns the snapshot URL for a channel.
func (c *Client) GetSnapshotURL(channelID string) string {
	return c.baseURL + "/channels/" + url.PathEscape(channelID) + "/snapshot"
}

// Snapshot captures a JPEG snapshot with auth headers.
func (c *Client) Snapshot(ctx context.Context, channelID string) ([]byte, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	escaped := url.PathEscape(channelID)
	for _, path := range []string{"/api/channels/%s/snapshot", "/channels/%s/snapshot"} {
		u := c.baseURL + fmt.Sprintf(path, escaped)
		req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, nil)
		if err != nil {
			continue
		}
		c.setAuthHeaders(req)
		resp, err := c.client.Do(req)
		if err != nil {
			continue
		}
		defer resp.Body.Close()
		if resp.StatusCode < 400 {
			return io.ReadAll(io.LimitReader(resp.Body, 10<<20))
		}
	}
	return nil, fmt.Errorf("Snapshot %s: all endpoints failed", channelID)
}

// ─── PTZ Control ────────────────────────────────────────────────────────────

// PTZControl sends a PTZ command (left/right/up/down/zoom_in/zoom_out/stop).
func (c *Client) PTZControl(ctx context.Context, channelID, command string, speed int) error {
	if err := c.EnsureLogin(ctx); err != nil {
		return err
	}

	if speed <= 0 {
		speed = 4
	}
	if speed > 8 {
		speed = 8
	}

	data, _ := json.Marshal(map[string]interface{}{
		"channel_id": channelID,
		"command":    command,
		"speed":      speed,
	})

	for _, path := range []string{"/api/ptz/control", "/ptz/control"} {
		_, err := c.doPostAuth(ctx, c.baseURL+path, data)
		if err == nil {
			return nil
		}
	}
	return fmt.Errorf("PTZControl: endpoint unavailable")
}

// ─── RTSP URL resolution (with cache) ───────────────────────────────────────

// ResolveRTSP returns the RTSP URL for a channel (cached for cfg.CacheTTL).
// This is the primary entry point for Hub's camera assignment flow.
func (c *Client) ResolveRTSP(ctx context.Context, channelID string) (string, error) {
	// Check cache first
	if cached := c.getCachedRTSP(channelID); cached != "" {
		return cached, nil
	}

	result, err := c.PlayChannel(ctx, channelID)
	if err != nil {
		return "", fmt.Errorf("resolve RTSP for %s: %w", channelID, err)
	}

	rtspURL := c.extractBestURL(result)
	if rtspURL == "" {
		return "", fmt.Errorf("no usable stream URL for %s", channelID)
	}

	// Normalize: replace localhost/127.0.0.1 with OWL server's actual host.
	// When OWL+ZLM runs on Hub machine, ZLM may return rtsp://127.0.0.1:554/...
	// but Workers on other machines cannot reach 127.0.0.1.
	rtspURL = c.normalizeStreamURL(rtspURL)

	c.setCachedRTSP(channelID, rtspURL)
	log.Printf("[owl] resolved RTSP for %s: %s", channelID, rtspURL)
	return rtspURL, nil
}

// normalizeStreamURL replaces localhost/127.0.0.1 in a stream URL with the
// OWL server's actual host, so Workers on other machines can reach ZLM.
func (c *Client) normalizeStreamURL(rawURL string) string {
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return rawURL
	}

	host := parsed.Hostname()
	if host != "127.0.0.1" && host != "localhost" && host != "::1" {
		return rawURL // already a reachable address
	}

	// Extract the actual host from OWL config URL
	owlParsed, err := url.Parse(c.baseURL)
	if err != nil {
		return rawURL
	}
	owlHost := owlParsed.Hostname()
	if owlHost == "" || owlHost == "127.0.0.1" || owlHost == "localhost" || owlHost == "::1" {
		return rawURL // OWL itself is also localhost, can't improve
	}

	// Replace host, preserve port
	port := parsed.Port()
	if port != "" {
		parsed.Host = owlHost + ":" + port
	} else {
		parsed.Host = owlHost
	}
	log.Printf("[owl] normalized stream URL: %s → %s", rawURL, parsed.String())
	return parsed.String()
}

// InvalidateRTSPCache removes a cached RTSP URL for a channel.
func (c *Client) InvalidateRTSPCache(channelID string) {
	c.cacheMu.Lock()
	delete(c.rtspCache, channelID)
	c.cacheMu.Unlock()
}

func (c *Client) getCachedRTSP(channelID string) string {
	c.cacheMu.RLock()
	defer c.cacheMu.RUnlock()
	entry, ok := c.rtspCache[channelID]
	if !ok || time.Now().After(entry.expiresAt) {
		return ""
	}
	return entry.url
}

func (c *Client) setCachedRTSP(channelID, rtspURL string) {
	c.cacheMu.Lock()
	defer c.cacheMu.Unlock()

	// GC: evict expired entries
	now := time.Now()
	for k, v := range c.rtspCache {
		if now.After(v.expiresAt) {
			delete(c.rtspCache, k)
		}
	}

	// Capacity limit: evict oldest if at max
	if len(c.rtspCache) >= maxCacheSize {
		var oldestKey string
		var oldestTime time.Time
		for k, v := range c.rtspCache {
			if oldestKey == "" || v.expiresAt.Before(oldestTime) {
				oldestKey = k
				oldestTime = v.expiresAt
			}
		}
		if oldestKey != "" {
			delete(c.rtspCache, oldestKey)
		}
	}

	c.rtspCache[channelID] = &rtspCacheEntry{
		url:       rtspURL,
		expiresAt: now.Add(c.cfg.CacheTTL),
	}
}

// ExtractBestURL is the public wrapper for extractBestURL.
func (c *Client) ExtractBestURL(result *PlayResult) string {
	return c.extractBestURL(result)
}

// extractBestURL picks the best URL from PlayResult: RTSP > RTMP > HTTP-FLV > HLS.
func (c *Client) extractBestURL(result *PlayResult) string {
	// Try items array first (rivision_owl format)
	if len(result.Items) > 0 {
		it := result.Items[0]
		for _, u := range []string{it.RTSP, it.RTMP, it.HTTP, it.HTTPFLV, it.HLS, it.WebRTC} {
			if u != "" {
				return u
			}
		}
	}
	// Try flat URLs map (GoWVP format)
	if len(result.URLs) > 0 {
		for _, key := range []string{"rtsp", "rtmp", "http_flv", "hls", "webrtc"} {
			if u, ok := result.URLs[key]; ok && u != "" {
				return u
			}
		}
	}
	return ""
}

// ─── ONVIF Discovery ────────────────────────────────────────────────────────

// DiscoverONVIF triggers ONVIF device discovery via SSE.
func (c *Client) DiscoverONVIF(ctx context.Context) ([]json.RawMessage, error) {
	if err := c.EnsureLogin(ctx); err != nil {
		return nil, err
	}

	for _, path := range []string{"/api/onvif/discover", "/onvif/discover"} {
		u := c.baseURL + path
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
		if err != nil {
			continue
		}
		c.setAuthHeaders(req)
		req.Header.Set("Accept", "text/event-stream")

		resp, err := c.client.Do(req)
		if err != nil {
			continue
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 400 {
			continue
		}

		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		var results []json.RawMessage
		for _, line := range strings.Split(string(body), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "data: ") {
				data := strings.TrimPrefix(line, "data: ")
				results = append(results, json.RawMessage(data))
			}
		}
		return results, nil
	}
	return nil, fmt.Errorf("ONVIF discover: endpoint unavailable")
}

// ─── Health Check ───────────────────────────────────────────────────────────

// Ping checks if OWL is reachable.
func (c *Client) Ping(ctx context.Context) error {
	for _, path := range []string{"/devices?page=1&size=1", "/api/devices?page=1&size=1", "/health"} {
		_, err := c.doGet(ctx, c.baseURL+path)
		if err == nil {
			return nil
		}
	}
	return fmt.Errorf("OWL unreachable at %s", c.baseURL)
}

// ─── Response parsers ───────────────────────────────────────────────────────

// parseResponse auto-detects wrapped {code,data} vs direct response.
// Returns the "payload" (either .data or the raw body).
func (c *Client) parseResponse(body []byte) (json.RawMessage, error) {
	var wrapped struct {
		Code int             `json:"code"`
		Msg  string          `json:"msg"`
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(body, &wrapped); err == nil {
		hasWrapped := len(wrapped.Data) > 0 || wrapped.Msg != "" || strings.Contains(string(body), `"code"`)
		if hasWrapped {
			if wrapped.Code != 0 && wrapped.Code != 200 {
				return nil, fmt.Errorf("OWL error %d: %s", wrapped.Code, wrapped.Msg)
			}
			if len(wrapped.Data) > 0 {
				return wrapped.Data, nil
			}
		}
	}
	// Direct format
	return json.RawMessage(body), nil
}

func (c *Client) parseDeviceList(body []byte) ([]Device, error) {
	parsed, err := c.parseResponse(body)
	if err != nil {
		return nil, err
	}

	// Try direct array
	var devices []Device
	if json.Unmarshal(parsed, &devices) == nil && len(devices) > 0 {
		return devices, nil
	}

	// Try {items: [...]} wrapper
	var wrapper struct {
		Items   []Device `json:"items"`
		Devices []Device `json:"devices"`
		Total   int      `json:"total"`
	}
	if json.Unmarshal(parsed, &wrapper) == nil {
		if len(wrapper.Items) > 0 {
			return wrapper.Items, nil
		}
		if len(wrapper.Devices) > 0 {
			return wrapper.Devices, nil
		}
	}

	// Try top-level items (non-wrapped response)
	var topLevel struct {
		Items []Device `json:"items"`
		Total int      `json:"total"`
	}
	if json.Unmarshal(body, &topLevel) == nil && len(topLevel.Items) > 0 {
		return topLevel.Items, nil
	}

	return nil, fmt.Errorf("cannot parse device list")
}

func (c *Client) parseChannelList(body []byte) ([]Channel, error) {
	parsed, err := c.parseResponse(body)
	if err != nil {
		return nil, err
	}

	var channels []Channel
	if json.Unmarshal(parsed, &channels) == nil && len(channels) > 0 {
		return channels, nil
	}

	var wrapper struct {
		Items    []Channel `json:"items"`
		Channels []Channel `json:"channels"`
		Total    int       `json:"total"`
	}
	if json.Unmarshal(parsed, &wrapper) == nil {
		if len(wrapper.Items) > 0 {
			return wrapper.Items, nil
		}
		if len(wrapper.Channels) > 0 {
			return wrapper.Channels, nil
		}
	}

	var topLevel struct {
		Items []Channel `json:"items"`
		Total int       `json:"total"`
	}
	if json.Unmarshal(body, &topLevel) == nil && len(topLevel.Items) > 0 {
		return topLevel.Items, nil
	}

	return nil, fmt.Errorf("cannot parse channel list")
}

func (c *Client) parsePlayResult(body []byte) (*PlayResult, error) {
	parsed, err := c.parseResponse(body)
	if err != nil {
		return nil, err
	}

	// Standard format: {app, stream, items: [{rtsp, ...}]}
	var result PlayResult
	if json.Unmarshal(parsed, &result) == nil {
		if len(result.Items) > 0 || len(result.URLs) > 0 {
			return &result, nil
		}
	}

	// GoWVP compat: {app, stream, urls: {rtsp: "...", ...}}
	var goWVP struct {
		App    string            `json:"app"`
		Stream string            `json:"stream"`
		URLs   map[string]string `json:"urls"`
	}
	if json.Unmarshal(parsed, &goWVP) == nil && len(goWVP.URLs) > 0 {
		return &PlayResult{App: goWVP.App, Stream: goWVP.Stream, URLs: goWVP.URLs}, nil
	}

	return nil, fmt.Errorf("cannot parse play result")
}

// ─── HTTP helpers with auth ─────────────────────────────────────────────────

func (c *Client) setAuthHeaders(req *http.Request) {
	c.mu.RLock()
	token := c.token
	c.mu.RUnlock()
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	req.Header.Set("User-Agent", "rivision-hub/owl-client")
}

func (c *Client) doGet(ctx context.Context, rawURL string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, err
	}
	return c.doRequest(req)
}

func (c *Client) doGetAuth(ctx context.Context, rawURL string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, err
	}
	c.setAuthHeaders(req)
	return c.doRequest(req)
}

// doGetAuthRetry does GET with auth, and retries once after re-login on 401.
func (c *Client) doGetAuthRetry(ctx context.Context, rawURL string) ([]byte, error) {
	body, err := c.doGetAuth(ctx, rawURL)
	if err != nil && c.isAuthError(err) {
		c.clearToken()
		if loginErr := c.Login(ctx); loginErr == nil {
			return c.doGetAuth(ctx, rawURL)
		}
	}
	return body, err
}

func (c *Client) doPostAuth(ctx context.Context, rawURL string, body []byte) ([]byte, error) {
	var bodyReader io.Reader
	if body != nil {
		bodyReader = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, rawURL, bodyReader)
	if err != nil {
		return nil, err
	}
	c.setAuthHeaders(req)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	return c.doRequest(req)
}

// doPostAuthRetry does POST with auth, retries once after re-login on 401.
func (c *Client) doPostAuthRetry(ctx context.Context, rawURL string, body []byte) ([]byte, error) {
	respBody, err := c.doPostAuth(ctx, rawURL, body)
	if err != nil && c.isAuthError(err) {
		c.clearToken()
		if loginErr := c.Login(ctx); loginErr == nil {
			return c.doPostAuth(ctx, rawURL, body)
		}
	}
	return respBody, err
}

func (c *Client) doDeleteAuth(ctx context.Context, rawURL string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, rawURL, nil)
	if err != nil {
		return nil, err
	}
	c.setAuthHeaders(req)
	respBody, err := c.doRequest(req)
	if err != nil && c.isAuthError(err) {
		c.clearToken()
		if loginErr := c.Login(ctx); loginErr == nil {
			req2, _ := http.NewRequestWithContext(ctx, http.MethodDelete, rawURL, nil)
			c.setAuthHeaders(req2)
			return c.doRequest(req2)
		}
	}
	return respBody, err
}

// doPostRaw does POST without auth headers (used for login).
func (c *Client) doPostRaw(ctx context.Context, rawURL string, data interface{}) ([]byte, error) {
	jsonData, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, rawURL, bytes.NewReader(jsonData))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", "rivision-hub/owl-client")
	return c.doRequest(req)
}

func (c *Client) doRequest(req *http.Request) ([]byte, error) {
	resp, err := c.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 2<<20))
	if err != nil {
		return nil, err
	}

	if resp.StatusCode >= 400 {
		return body, fmt.Errorf("OWL API %s %s: HTTP %d: %s",
			req.Method, req.URL.Path, resp.StatusCode, strings.TrimSpace(string(body)))
	}
	return body, nil
}

func (c *Client) isAuthError(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.Contains(msg, "HTTP 401") || strings.Contains(msg, "HTTP 403")
}
