#include "actions.h"
#include "vlm/vlm_client.h"
#include "utils/logger.h"
#include <sstream>
#include <regex>

namespace rivision::core {

ActionExecutor::ActionExecutor() = default;
ActionExecutor::~ActionExecutor() = default;

ActionExecutor::VlmVerifyResult ActionExecutor::executeVlmVerify(
    const RuleConfig::Action& action,
    const Frame& frame,
    const Detection& detection
) {
    VlmVerifyResult result;
    
    if (!vlm_client_) {
        LOG_WARN("VLM client not set, skipping verify");
        result.timeout = true;
        return result;
    }
    
    std::string prompt = action.prompt;
    if (prompt.empty()) {
        prompt = "Is this a valid security alert? Describe what you see.";
    }
    
    try {
        // Set timeout before analyze call
        if (action.vlm_timeout_ms > 0) {
            vlm_client_->setTimeout(action.vlm_timeout_ms);
        }
        
        auto response = vlm_client_->analyze(frame, prompt);
        
        if (!response.timeout && !response.description.empty()) {
            result.verified = true;
            result.confidence = action.default_confidence;  // Use configurable confidence
            result.description = response.description;
        } else {
            result.timeout = response.timeout;
        }
        
    } catch (const std::exception& e) {
        LOG_ERROR("VLM verify failed: {}", e.what());
        result.timeout = true;
    }
    
    return result;
}

void ActionExecutor::executeRecord(
    const RuleConfig::Action& action,
    const StreamId& stream_id,
    const AlertEvent& alert
) {
    if (!record_callback_) {
        LOG_WARN("Record callback not set");
        return;
    }
    
    RecordRequest req;
    req.stream_id = stream_id;
    req.pre_sec = action.pre_sec;
    req.post_sec = action.post_sec;
    req.output_path = ""; // Will be generated by recording manager
    
    record_callback_(req);
    
    LOG_DEBUG("Recording triggered for stream {} (pre={}, post={})",
        stream_id, action.pre_sec, action.post_sec);
}

void ActionExecutor::executeNotify(
    const RuleConfig::Action& action,
    const AlertEvent& alert
) {
    if (!notify_callback_) {
        LOG_WARN("Notify callback not set");
        return;
    }
    
    NotifyRequest req;
    req.alert = alert;
    req.channels = action.channels;
    req.message = renderMessage(action.content, alert);
    
    notify_callback_(req);
    
    LOG_DEBUG("Notification triggered for alert {}", alert.id);
}

std::string ActionExecutor::renderMessage(
    const std::string& template_str,
    const AlertEvent& alert
) {
    if (template_str.empty()) {
        std::ostringstream oss;
        oss << "[" << alertLevelToString(alert.level) << "] "
            << alert.rule_name << " - "
            << alert.trigger_type;
        if (!alert.zone_name.empty()) {
            oss << " in " << alert.zone_name;
        }
        oss << " at " << timestampToIso8601(alert.timestamp);
        return oss.str();
    }
    
    std::string result = template_str;
    
    auto replace = [&result](const std::string& token, const std::string& value) {
        size_t pos = 0;
        while ((pos = result.find(token, pos)) != std::string::npos) {
            result.replace(pos, token.length(), value);
            pos += value.length();
        }
    };
    
    replace("{{alert_id}}", alert.id);
    replace("{{rule_name}}", alert.rule_name);
    replace("{{level}}", alertLevelToString(alert.level));
    replace("{{trigger_type}}", alert.trigger_type);
    replace("{{zone_name}}", alert.zone_name);
    replace("{{camera_id}}", alert.camera_id);
    replace("{{timestamp}}", timestampToIso8601(alert.timestamp));
    replace("{{direction}}", alert.direction);
    
    return result;
}

} // namespace rivision::core
